# makefile @ assembly folder

SHELL = /bin/bash

bin_path := ../../$(bin_path)/kernel/assembly/
src_path := ../../$(src_path)

sources_to_filter_out = debug_files_content.asm

include ../../assembly_general_makefile
include ../../general_makefile
