# makefile @ common folder

SHELL = /bin/bash

dep_path := ../$(dep_path)/common/
bin_path_base := ../$(bin_path_base)
bin_path := ../$(bin_path)/common/

include ../general_makefile
include ../c_general_makefile
